name: Dagger.io - Hello World
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: 'Greeting'
        required: true

      name:
        type: string
        description: 'Name'
        required: true


jobs:
  hello_dagger_demo:
    runs-on:  [ubuntu-latest]
    steps:
        - name: Checkout 
          uses: actions/checkout@v4 
                    
        - name: Run Dagger
          uses: dagger/dagger-for-github@v5
          with:
            workdir: ${{github.workspace}}/dagger_io/demo
            version: latest
            module: demo
            verb: call
            args: hello --greeting="${{github.event.inputs.greeting}}" --name="${{github.event.inputs.name}}" 
            cloud-token: ${{secrets.DAGGER_TOKEN}}